// controllers/moodController.js
import Mood from "../models/Mood.js";
import TodayGoal from "../models/todayGoal.js";
import moment from "moment";

// ✅ Save mood entry + automatically mark quiz as completed
export const saveMood = async (req, res) => {
  try {
    const { mood, score, note } = req.body;
    const userId = req.user.id; // from verifyToken

    if (!mood) {
      return res.status(400).json({ message: "Mood is required." });
    }

    // ✅ Create mood record (createdAt auto-generated by schema)
    const newMood = await Mood.create({
      userId,
      mood,
      score,
      note,
    });

    // ✅ Mark Quiz completed for TodayGoal
    const today = moment().format("YYYY-MM-DD");

    await TodayGoal.findOneAndUpdate(
      { userId, date: today },
      { quizCompleted: true },
      { new: true }
    );

    res.status(201).json({
      message: "Mood recorded & quiz marked completed ✅",
      mood: newMood,
    });
  } catch (error) {
    console.error("Mood save error:", error);
    res.status(500).json({ message: "Server error", error });
  }
};


// ✅ Get today's mood based on createdAt timestamp
export const getTodayMood = async (req, res) => {
  try {
    const userId = req.user.id;

    const startOfDay = moment().startOf("day").toDate();
    const endOfDay = moment().endOf("day").toDate();

    const mood = await Mood.findOne({
      userId,
      createdAt: { $gte: startOfDay, $lte: endOfDay }, // ✅ compare timestamps
    }).sort({ createdAt: -1 }); // get latest one if multiple

    res.status(200).json({ mood });
  } catch (error) {
    console.error("Error fetching mood:", error);
    res.status(500).json({ message: "Server error", error });
  }
};
